brew "neovim"
brew "tmux"
brew "direnv"
brew "asdf"
brew "fzf"
brew "zoxide"
brew "bat"
brew "glow" # render markdown in the terminal
brew "eza"
brew "ripgrep"
brew "dotnet"
brew "overmind"
brew "pnpm"
brew "googleworkspace-cli" # gws: official Google Workspace admin CLI
cask "antigravity-cli"
cask "gcloud-cli"
cask "font-dejavu-sans-mono-nerd-font"
