# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="sorin"

# Disable command autocorrection
DISABLE_CORRECTION="true"

# Plugins (custom/*.zsh files are sourced automatically by oh-my-zsh)
plugins=(git macos)

set -k

source $ZSH/oh-my-zsh.sh

source "$HOME/.zsh/exports.zsh"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/homebrew/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/homebrew/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/opt/homebrew/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/opt/homebrew/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

export PATH="$HOME/.local/bin:$PATH"

# fzf shell integration (ctrl-r history, ctrl-t file finder)
eval "$(fzf --zsh)"

# zoxide smart cd (use: z <directory>)
eval "$(zoxide init zsh)"
