# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="guero"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable command autocorrection
DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(git osx)

set -k
setopt rcquotes

# Helpful aliases
alias b="bundle"
alias n="node"
alias nye="npm i" # bill bill bill!
alias :q="exit"
alias :l="tail -n1000 -f $@"
alias :p="ps aux | grep -v grep | grep $@ -i --color=auto"

export EDITOR='vim'

# default filetype actions
alias -s js="vim"
alias -s jsx="vim"
alias -s coffee="vim"
alias -s rb="vim"
alias -s haml="vim"
alias -s pdf="open"

source $ZSH/oh-my-zsh.sh

source "$HOME/.zsh/aliases.zsh"
source "$HOME/.zsh/exports.zsh"
